switch_cible:
  connection_options:
    netmiko:
      extras:
        disabled_algorithms:
          pubkeys:
          - rsa-sha2-256
          - rsa-sha2-512
        global_delay_factor: 2
        secret: cisco1
  hostname: 10.10.10.50
  password: admin123
  platform: ios
  port: 22
  username: admin
